CREATE TABLE [dbo].[BusinessRelation]
(
	[BusinessRelation_SK] INT NOT NULL, 
    [Name] NVARCHAR(80) NULL, 
    [Address] NVARCHAR(256) NULL, 
    [ZipCode] NVARCHAR(10) NULL, 
    [City] NVARCHAR(80) NULL, 
    [Country] NVARCHAR(80) NULL,
CONSTRAINT [PK_BUSINESS_RELATION] PRIMARY KEY CLUSTERED
(
    BusinessRelation_SK ASC
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
